name: ObsidianDestroyer
main: com.drtshock.obsidiandestroyer.ObsidianDestroyer
version: 1.0
authors: [drtshock, squidicuz, Omnivion]

commands:
    od:
        description: ObsidianDestroyer command.
        usage: /<command> <reload | reloadDB | reset | version>
        aliases: [obsidiandestroyer]
        permission: obsidiandestroyer.admin
permissions:
    obsidiandestroyer.admin:
      default: op
      description: Allow you to use all admin commands for this plugin.
    obsidiandestroyer.check:
      default: true
      description: Allow you to check the durability of a block with an item.
